"""Auto-generated by build_capstone_checkpoints.py (Checkpoint 1.1 starter).
Jupytext-style cell markers (# %% / # %% [markdown]) — runnable as a
plain script AND openable as cells in VS Code / PyCharm / Jupytext.
"""

# This is a copy of the main script — keep it in the checkpoint folder for upload.

from pathlib import Path

print("See parent README for instructions. This is a copy of the baseline script.")

# Original file is in the project root; keep this copy for repository organization.
